/**
 * @file TMR_Config.h
 * @author Ahmed Atia (atiaa6501@gmail.com)
 * 
 * @version 1.0
 * @date 2022-11-12
 * 
 * @copyright Copyright (c) 2022
 * 
 */


#ifndef TMR_CONFIG_H_
#define TMR_CONFIG_H_
#include "TMR_Private.h"

/**********************************************TIMER 0**********************************************/
#define TMR_TIMER0_OVERFLOW_COUNTER	        977
#define TMR_TIMER0_CTC_COUNTER		        3000
/*
        Timer0 modes of operation
1) TMR_TIMER0_NORMAL_MODE           
2) TMR_TIMER0_CTC_MODE              
3) TMR_TIMER0_FAST_PWM_MODE         
4) TMR_TIMER0_PHASE_CORRECT_PWM_MODE
*/
#define TMR_TIMER0_MODE                         TMR_TIMER0_CTC_MODE
/*      Timer 0 Interrupt Status
1) TMR_TIMER0_INTERRUPT_ENABLED 
2) TMR_TIMER0_INTERRUPT_DISABLED
*/
#define TMR_TIMER0_INTERRUPT_STATUS             TMR_TIMER0_INTERRUPT_ENABLED

/*
        Modes of Fast PWM
1) TMR_TIMER0_FAST_PWM_NON_INVERTING_MODE
2) TMR_TIMER0_FAST_PWM_INVERTING_MODE    
*/
#define TMR_TIMER0_FAST_PWM_OPERATION           TMR_TIMER0_FAST_PWM_NON_INVERTING_MODE
/*
        Modes of Phase Corret PWM
1) TMR_TIMER0_PHASE_CORRECT_PWM_NON_INVERTING_MODE     
2) TMR_TIMER0_PHASE_CORRECT_PWM_INVERTING_MODE 
*/
#define TMR_TIMER0_PHASE_CORRECT_PWM_OPERATION  TMR_TIMER0_PHASE_CORRECT_PWM_NON_INVERTING_MODE

/*
        Clock Prescalars               
1) TMR_PRESCALAR_DIVIDE_BY_1         
2) TMR_PRESCALAR_DIVIDE_BY_8         
3) TMR_PRESCALAR_DIVIDE_BY_64        
4) TMR_PRESCALAR_DIVIDE_BY_256       
5) TMR_PRESCALAR_DIVIDE_BY_1024      
6) TMR_EXTERNAL_CLOCK_ON_FALLING_EDGE
7) TMR_EXTERNAL_CLOCK_ON_RISING_EDGE 
*/
#define TMR_TIMER0_PRESCALAR                    TMR_PRESCALAR_DIVIDE_BY_64

/**********************************************TIMER 1**********************************************/
/*
        Timer 1 modes of operation
1) TMR_TIMER1_NORMAL_MODE                         
2) TMR_TIMER1_CTC_MODE                            
3) TMR_TIMER1_FAST_PWM_MODE                       
4) TMR_TIMER1_PHASE_CORRECT_PWM_MODE              
*/
#define TMR_TIMER1_MODE                         TMR_TIMER1_FAST_PWM_MODE                        
/*
        Clock Prescalars               
1) TMR_PRESCALAR_DIVIDE_BY_1         
2) TMR_PRESCALAR_DIVIDE_BY_8         
3) TMR_PRESCALAR_DIVIDE_BY_64        
4) TMR_PRESCALAR_DIVIDE_BY_256       
5) TMR_PRESCALAR_DIVIDE_BY_1024      
6) TMR_EXTERNAL_CLOCK_ON_FALLING_EDGE
7) TMR_EXTERNAL_CLOCK_ON_RISING_EDGE 
*/
#define TMR_TIMER1_PRESCALAR                    TMR_PRESCALAR_DIVIDE_BY_64       
/*
        Modes of Fast PWM
1) TMR_TIMER1_FAST_PWM_NON_INVERTING_MODE
2) TMR_TIMER1_FAST_PWM_INVERTING_MODE    
*/
#define TMR_TIMER1_FAST_PWM_OPERATION           TMR_TIMER1_FAST_PWM_NON_INVERTING_MODE

/*      Modes of Phase Correct PWM
1) TMR_TIMER1_PHASE_CORRECT_PWM_NON_INVERTING_MODE
2) TMR_TIMER1_PHASE_CORRECT_PWM_INVERTING_MODE 
*/
#define TMR_TIMER1_PHASE_CORRECT_PWM_OPERATION  TMR_TIMER1_PHASE_CORRECT_PWM_NON_INVERTING_MODE

/*      Timer 1 Interrupt Status
1) TMR_TIMER1_INTERRUPT_ENABLED 
2) TMR_TIMER1_INTERRUPT_DISABLED
*/
#define TMR_TIMER1_INTERRUPT_STATUS             TMR_TIMER1_INTERRUPT_ENABLED
/**********************************************TIMER 2**********************************************/
/*
        Timer2 modes of operation
1) TMR_TIMER2_NORMAL_MODE
2) TMR_TIMER2_CTC_MODE
3) TMR_TIMER2_FAST_PWM_MODE
4) TMR_TIMER2_PHASE_CORRECT_PWM_MODE
*/
#define TMR_TIMER2_MODE                         TMR_TIMER2_FAST_PWM_MODE
/*
        Timer 2 Prescalars
1) TMR_PRESCALAR_DIVIDE_BY_1
2) TMR_PRESCALAR_DIVIDE_BY_8
3) TMR_PRESCALAR_DIVIDE_BY_32
4) TMR_PRESCALAR_DIVIDE_BY_64
5) TMR_PRESCALAR_DIVIDE_BY_128
6) TMR_PRESCALAR_DIVIDE_BY_256
7) TMR_PRESCALAR_DIVIDE_BY_1024
*/
#define TMR_TIMER2_PRESCALAR                    TMR_PRESCALAR_DIVIDE_BY_64
/*
        Timer 2 Interrupt Status
1) TMR_TIMER2_INTERRUPT_ENABLED
2) TMR_TIMER2_INTERRUPT_DISABLED
*/
#define TMR_TIMER2_INTERRUPT_STATUS             TMR_TIMER2_INTERRUPT_DISABLED
/*
        Modes of Fast PWM
1) TMR_TIMER2_FAST_PWM_NON_INVERTING_MODE
2) TMR_TIMER2_FAST_PWM_INVERTING_MODE
*/
#define TMR_TIMER2_FAST_PWM_OPERATION           TMR_TIMER2_FAST_PWM_NON_INVERTING_MODE
/*
        Modes of Phase Correct PWM
1) TMR_TIMER2_PHASE_CORRECT_PWM_NON_INVERTING_MODE
2) TMR_TIMER2_PHASE_CORRECT_PWM_INVERTING_MODE
*/
#define TMR_TIMER2_PHASE_CORRECT_PWM_OPERATION  TMR_TIMER2_PHASE_CORRECT_PWM_NON_INVERTING_MODE
#endif /* TMR_CONFIG_H_ */