/**
 * @file ADC_Config.h
 * @author Ahmed Atia (atiaa6501@gmail.com)
 * 
 * @version 1.0
 * @date 2022-11-11
 * 
 * @copyright Copyright (c) 2023
 * 
 */
#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_

#include "ADC_Private.h"
/*Options For Voltage References
 *1-VREF_AREF_PIN
 *1-VREF_AVCC_PIN
 *1-VREF_2_56V_INTERNAL*/

#define ADC_SET_VREF            VREF_2_56V_INTERNAL

/*
1) ADC_INTERRUPT_ENABLED 
2) ADC_INTERRUPT_DISABLED
*/
#define ADC_INTERRUPT_STATUS    ADC_INTERRUPT_ENABLED
/*
    Options For Prescalar
1) PRESCALER_DIVIDE_BY_2
2) PRESCALER_DIVIDE_BY_4
3) PRESCALER_DIVIDE_BY_8
4) PRESCALER_DIVIDE_BY_16
5) PRESCALER_DIVIDE_BY_32
6) PRESCALER_DIVIDE_BY_64
7) PRESCALER_DIVIDE_BY_128
*/

#define ADC_SET_PRESCALAR       PRESCALER_DIVIDE_BY_64

/*Options For Adjusting the ADC Register Value
 *1-ADC_RIGHT_ADJUST
 *1-ADC_LEFT_ADJUST*/

#define ADC_SET_ADJUST_LEVEL    ADC_RIGHT_ADJUST

/*
        ADC Conversion Mode
1) ADC_SINGLE_CONVERSION_MODE
2) ADC_AUTO_TRIGGER_MODE
*/
#define ADC_CONVERSION_MODE     ADC_SINGLE_CONVERSION_MODE

/*
        ADC Auto Trigger Source
1) ADC_FREE_RUNNING_MODE             
2) ADC_ANALOG_COMPARATOR_TRIGGER     
3) ADC_EXT_INT0_TRIGGER              
4) ADC_TIMER0_COMPARE_MATCH_TRIGGER  
5) ADC_TIMER0_OVERFLOW_TRIGGER       
6) ADC_TIMER1_COMPARE_MATCH_B_TRIGGER
7) ADC_TIMER1_OVERFLOW_TRIGGER       
8) ADC_TIMER1_CAPTURE_EVENT_TRIGGER  
*/
#define ADC_AUTO_TRIGGER_SOURCE ADC_TIMER0_OVERFLOW_TRIGGER
#endif /*ADC_CONFIG_H_*/